name: caffex_firebase
description: "CaffeX is a modern coffee ordering app built with Flutter and Firebase."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.14.4
  smooth_page_indicator: ^1.2.1
  get: ^4.7.2
  lottie: ^3.3.1
  flutter_native_splash: ^2.4.6
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/play_store_512.png"

flutter_native_splash:
  color: "#fdf6f0"
  image: "assets/icons/app_icon.png"
  android: true
  ios: false
  web: false
  fullscreen: true
  android_gravity: center

  android_12:
    color: "#fdf6f0"
    image: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/products/
    - assets/icons/
    - assets/animations/